name: insightiq_dbt
version: "1.0"
profile: insightiq

models:
  insightiq_dbt:
    +schema: "{{ var('tenant_schema', target.schema) }}"
    staging:
      +materialized: incremental
    marts:
      +materialized: incremental
    snapshots:
      +materialized: table
