insightiq:
  target: prod
  outputs:
    prod:
      type: postgres
      host: 66.135.22.167
      port: 5432
      user: postgres
      password: galaxiq
      dbname: galaxiq_tenants
      schema: public # This is a fallback; models should use the tenant_schema var
      threads: 4
