insightiq:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: nitizz
      password: ""
      dbname: brand_intelligence
      schema: analytics
      threads: 4
